-- Exported from current remote GaussDB for BookstoreManagementSystem.
-- Generated by local psycopg2 catalog exporter.
-- Target: restore into an empty or disposable database/schema.

SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;

DROP TABLE IF EXISTS "public"."users" CASCADE;
DROP TABLE IF EXISTS "public"."sales_order" CASCADE;
DROP TABLE IF EXISTS "public"."sales_detail" CASCADE;
DROP TABLE IF EXISTS "public"."purchase_order" CASCADE;
DROP TABLE IF EXISTS "public"."purchase_detail" CASCADE;
DROP TABLE IF EXISTS "public"."publisher" CASCADE;
DROP TABLE IF EXISTS "public"."inventory" CASCADE;
DROP TABLE IF EXISTS "public"."book_category" CASCADE;
DROP TABLE IF EXISTS "public"."book" CASCADE;
DROP SEQUENCE IF EXISTS "public"."sales_detail_item_id_seq" CASCADE;
DROP SEQUENCE IF EXISTS "public"."purchase_detail_item_id_seq" CASCADE;
DROP SEQUENCE IF EXISTS "public"."order_seq" CASCADE;

CREATE SEQUENCE "public"."order_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE "public"."purchase_detail_item_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE "public"."sales_detail_item_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE TABLE "public"."book" (
    "book_id" character varying(20) NOT NULL,
    "title" character varying(100) NOT NULL,
    "publisher_id" character varying(50) NOT NULL,
    "category_id" character varying(20) NOT NULL,
    "author" character varying(100),
    "retail_price" numeric(10,2) DEFAULT 0.00 NOT NULL
);

CREATE TABLE "public"."book_category" (
    "category_id" character varying(20) NOT NULL,
    "category_name" character varying(100)
);

CREATE TABLE "public"."inventory" (
    "book_id" character varying(20) NOT NULL,
    "stock_quantity" integer NOT NULL,
    "last_updated" timestamp without time zone DEFAULT pg_systimestamp() NOT NULL
);

CREATE TABLE "public"."publisher" (
    "publisher_id" character varying(50) NOT NULL,
    "address" character varying(100),
    "phone" character varying(20),
    "contact_person" character varying(50)
);

CREATE TABLE "public"."purchase_detail" (
    "item_id" character varying(50) NOT NULL,
    "order_id" character varying(20) NOT NULL,
    "book_id" character varying(20) NOT NULL,
    "quantity" integer NOT NULL,
    "purchase_price" numeric(10,2) NOT NULL
);

CREATE TABLE "public"."purchase_order" (
    "order_id" character varying(20) NOT NULL,
    "purchaser" character varying(50),
    "purchase_date" timestamp without time zone NOT NULL,
    "notes" character varying(200)
);

CREATE TABLE "public"."sales_detail" (
    "item_id" character varying(50) NOT NULL,
    "order_id" character varying(20) NOT NULL,
    "book_id" character varying(20) NOT NULL,
    "quantity" integer NOT NULL,
    "sale_price" numeric(10,2) NOT NULL
);

CREATE TABLE "public"."sales_order" (
    "order_id" character varying(20) NOT NULL,
    "customer" character varying(50),
    "sale_date" timestamp without time zone NOT NULL,
    "notes" character varying(200)
);

CREATE TABLE "public"."users" (
    "username" character varying(50) NOT NULL,
    "password" text NOT NULL,
    "role" character varying(50) NOT NULL
);

COMMENT ON TABLE "public"."book" IS '图书基本信息表';
COMMENT ON TABLE "public"."book_category" IS '图书分类表';
COMMENT ON TABLE "public"."inventory" IS '图书库存实时信息表';
COMMENT ON TABLE "public"."publisher" IS '出版社基本信息表';
COMMENT ON TABLE "public"."purchase_detail" IS '进货订单明细表';
COMMENT ON TABLE "public"."purchase_order" IS '图书进货订单主表';
COMMENT ON TABLE "public"."sales_detail" IS '销售订单明细表';
COMMENT ON TABLE "public"."sales_order" IS '图书销售订单主表';

COMMENT ON COLUMN "public"."book"."book_id" IS '图书唯一编号';
COMMENT ON COLUMN "public"."book"."title" IS '图书名称';
COMMENT ON COLUMN "public"."book"."publisher_id" IS '出版社ID';
COMMENT ON COLUMN "public"."book"."category_id" IS '图书类别ID';
COMMENT ON COLUMN "public"."book"."author" IS '作者信息';
COMMENT ON COLUMN "public"."book_category"."category_id" IS '图书类别ID';
COMMENT ON COLUMN "public"."book_category"."category_name" IS '类别名称';
COMMENT ON COLUMN "public"."publisher"."publisher_id" IS '出版社ID，主键';
COMMENT ON COLUMN "public"."publisher"."address" IS '出版社地址';
COMMENT ON COLUMN "public"."publisher"."phone" IS '联系电话';
COMMENT ON COLUMN "public"."publisher"."contact_person" IS '联系人';

ALTER TABLE ONLY "public"."book" ADD CONSTRAINT "book_pkey" PRIMARY KEY (book_id);
ALTER TABLE ONLY "public"."book_category" ADD CONSTRAINT "book_category_pkey" PRIMARY KEY (category_id);
ALTER TABLE ONLY "public"."inventory" ADD CONSTRAINT "inventory_pkey" PRIMARY KEY (book_id);
ALTER TABLE ONLY "public"."publisher" ADD CONSTRAINT "publisher_pkey" PRIMARY KEY (publisher_id);
ALTER TABLE ONLY "public"."purchase_detail" ADD CONSTRAINT "purchase_detail_pkey" PRIMARY KEY (item_id);
ALTER TABLE ONLY "public"."purchase_order" ADD CONSTRAINT "purchase_order_pkey" PRIMARY KEY (order_id);
ALTER TABLE ONLY "public"."sales_detail" ADD CONSTRAINT "sales_detail_pkey" PRIMARY KEY (item_id);
ALTER TABLE ONLY "public"."sales_order" ADD CONSTRAINT "sales_order_pkey" PRIMARY KEY (order_id);
ALTER TABLE ONLY "public"."users" ADD CONSTRAINT "users_pkey" PRIMARY KEY (username);

ALTER TABLE ONLY "public"."book" ADD CONSTRAINT "book_category_id_fkey" FOREIGN KEY (category_id) REFERENCES book_category(category_id);
ALTER TABLE ONLY "public"."book" ADD CONSTRAINT "book_publisher_id_fkey" FOREIGN KEY (publisher_id) REFERENCES publisher(publisher_id);
ALTER TABLE ONLY "public"."inventory" ADD CONSTRAINT "inventory_book_id_fkey" FOREIGN KEY (book_id) REFERENCES book(book_id);
ALTER TABLE ONLY "public"."purchase_detail" ADD CONSTRAINT "purchase_detail_book_id_fkey" FOREIGN KEY (book_id) REFERENCES book(book_id);
ALTER TABLE ONLY "public"."purchase_detail" ADD CONSTRAINT "purchase_detail_order_id_fkey" FOREIGN KEY (order_id) REFERENCES purchase_order(order_id);
ALTER TABLE ONLY "public"."sales_detail" ADD CONSTRAINT "sales_detail_book_id_fkey" FOREIGN KEY (book_id) REFERENCES book(book_id);
ALTER TABLE ONLY "public"."sales_detail" ADD CONSTRAINT "sales_detail_order_id_fkey" FOREIGN KEY (order_id) REFERENCES sales_order(order_id);

ALTER TABLE ONLY "public"."book" ADD CONSTRAINT "book_retail_price_check" CHECK (retail_price >= 0);
ALTER TABLE ONLY "public"."inventory" ADD CONSTRAINT "inventory_stock_quantity_check" CHECK (stock_quantity >= 0);
ALTER TABLE ONLY "public"."purchase_detail" ADD CONSTRAINT "purchase_detail_quantity_check" CHECK (quantity > 0);
ALTER TABLE ONLY "public"."purchase_detail" ADD CONSTRAINT "purchase_detail_price_check" CHECK (purchase_price >= 0);
ALTER TABLE ONLY "public"."sales_detail" ADD CONSTRAINT "sales_detail_quantity_check" CHECK (quantity > 0);
ALTER TABLE ONLY "public"."sales_detail" ADD CONSTRAINT "sales_detail_price_check" CHECK (sale_price >= 0);
ALTER TABLE ONLY "public"."users" ADD CONSTRAINT "users_role_check" CHECK (role IN ('sys_admin', 'procurement_officer', 'warehouse_keeper', 'sales_agent', 'finance_officer'));

CREATE INDEX "idx_book_category_id" ON "public"."book" (category_id);
CREATE INDEX "idx_book_publisher_id" ON "public"."book" (publisher_id);
CREATE INDEX "idx_inventory_stock_quantity" ON "public"."inventory" (stock_quantity);
CREATE INDEX "idx_purchase_order_date" ON "public"."purchase_order" (purchase_date);
CREATE INDEX "idx_purchase_detail_order_id" ON "public"."purchase_detail" (order_id);
CREATE INDEX "idx_purchase_detail_book_id" ON "public"."purchase_detail" (book_id);
CREATE INDEX "idx_sales_order_date" ON "public"."sales_order" (sale_date);
CREATE INDEX "idx_sales_detail_order_id" ON "public"."sales_detail" (order_id);
CREATE INDEX "idx_sales_detail_book_id" ON "public"."sales_detail" (book_id);
CREATE INDEX "idx_users_role" ON "public"."users" (role);


