-- Exported from current remote GaussDB for BookstoreManagementSystem.
-- Generated by local psycopg2 catalog exporter.
-- Run after 01_schema.sql and 02_data.sql.

SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;

DROP VIEW IF EXISTS "public"."v_publisher_supply" CASCADE;
DROP VIEW IF EXISTS "public"."v_num_book_cat" CASCADE;
DROP VIEW IF EXISTS "public"."v_low_quantity_books" CASCADE;
DROP VIEW IF EXISTS "public"."v_bestsellers" CASCADE;
DROP FUNCTION IF EXISTS "public"."update_inventory_on_sale"() CASCADE;
DROP FUNCTION IF EXISTS "public"."update_inventory_on_purchase"() CASCADE;
DROP FUNCTION IF EXISTS "public"."get_book_stats_by_period"(start_date timestamp without time zone, end_date timestamp without time zone) CASCADE;
DROP PROCEDURE IF EXISTS "public"."generate_sales_order"(customer character varying, note text, book_ids character varying[], quantities integer[], prices numeric[], sales_date timestamp without time zone) CASCADE;
DROP PROCEDURE IF EXISTS "public"."generate_purchase_order"(purchaser character varying, note text, book_ids character varying[], quantities integer[], prices numeric[], purchase_date timestamp without time zone) CASCADE;

-- Procedures and functions
CREATE OR REPLACE PROCEDURE public.generate_purchase_order(
    purchaser VARCHAR, 
    note TEXT,
    book_ids VARCHAR[], 
    quantities INT[],
    prices NUMERIC[], 
  	purchase_date TIMESTAMP
)
AS 
DECLARE
    order_id VARCHAR := 'PO-' || nextval('order_seq');
    detail_id INT;
BEGIN
    INSERT INTO purchase_order (order_id, purchaser, purchase_date, notes)
    VALUES (order_id, purchaser, purchase_date, note);

    FOR i IN 1..array_length(book_ids, 1) LOOP
    	detail_id := nextval('purchase_detail_item_id_seq');
        INSERT INTO purchase_detail (item_id, order_id, book_id, quantity, purchase_price)
        VALUES (detail_id, order_id, book_ids[i], quantities[i], prices[i]);
    END LOOP;
END;
/

CREATE OR REPLACE PROCEDURE public.generate_sales_order(
    customer VARCHAR, 
    note TEXT,
    book_ids VARCHAR[], 
    quantities INT[], 
  	prices NUMERIC[], 
  	sales_date TIMESTAMP
)
AS 
DECLARE
    order_id VARCHAR := 'SO-' || nextval('order_seq');
    detail_id INT;
BEGIN
    INSERT INTO sales_order (order_id, customer, sale_date, notes)
    VALUES (order_id, customer, sales_date, note);

    FOR i IN 1..array_length(book_ids, 1) LOOP
    	detail_id := nextval('sales_detail_item_id_seq');
        INSERT INTO sales_detail (item_id, order_id, book_id, quantity, sale_price)
        VALUES (detail_id, order_id, book_ids[i], quantities[i], prices[i]);
    END LOOP;
END;
/

CREATE OR REPLACE FUNCTION public.get_book_stats_by_period(start_date timestamp without time zone, end_date timestamp without time zone)
 RETURNS TABLE(book_id character varying, title character varying, author character varying, category_name character varying, purchase_quantity bigint, purchase_amount numeric, sales_quantity bigint, sales_amount numeric, current_stock integer)
 LANGUAGE plpgsql
 NOT FENCED NOT SHIPPABLE
AS $function$
BEGIN
    RETURN QUERY
    SELECT 
        b.book_id,
        b.title,
        b.author,
        bc.category_name,
        COALESCE(SUM(CASE WHEN po.purchase_date BETWEEN start_date AND end_date THEN pd.quantity ELSE 0 END), 0)::bigint AS purchase_quantity,
        COALESCE(SUM(CASE WHEN po.purchase_date BETWEEN start_date AND end_date THEN pd.quantity * pd.purchase_price ELSE 0 END), 0)::numeric AS purchase_amount,
        COALESCE(SUM(CASE WHEN so.sale_date BETWEEN start_date AND end_date THEN sd.quantity ELSE 0 END), 0)::bigint AS sales_quantity,
        COALESCE(SUM(CASE WHEN so.sale_date BETWEEN start_date AND end_date THEN sd.quantity * b.retail_price ELSE 0 END), 0)::numeric AS sales_amount,
        COALESCE(i.stock_quantity, 0) AS current_stock
    FROM 
        book b
    JOIN 
        book_category bc ON b.category_id = bc.category_id
    LEFT JOIN 
        purchase_detail pd ON b.book_id = pd.book_id
    LEFT JOIN 
        purchase_order po ON pd.order_id = po.order_id
    LEFT JOIN 
        sales_detail sd ON b.book_id = sd.book_id
    LEFT JOIN 
        sales_order so ON sd.order_id = so.order_id
    LEFT JOIN 
        inventory i ON b.book_id = i.book_id
    GROUP BY 
        b.book_id, b.title, b.author, bc.category_name, i.stock_quantity
    ORDER BY 
        purchase_quantity DESC;
END;
$function$;

CREATE OR REPLACE FUNCTION public.update_inventory_on_purchase()
 RETURNS trigger
 LANGUAGE plpgsql
 NOT FENCED NOT SHIPPABLE
AS $function$
BEGIN
    -- 检查库存记录是否存在
    IF NOT EXISTS (SELECT 1 FROM inventory WHERE book_id = NEW.book_id) THEN
        INSERT INTO inventory (book_id, stock_quantity, last_updated)
        VALUES (NEW.book_id, NEW.quantity, NOW());
    ELSE
        UPDATE inventory 
        SET stock_quantity = stock_quantity + NEW.quantity,
            last_updated = NOW()
        WHERE book_id = NEW.book_id;
    END IF;
    
    RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.update_inventory_on_sale()
 RETURNS trigger
 LANGUAGE plpgsql
 NOT FENCED NOT SHIPPABLE
AS $function$
DECLARE
    current_stock INT;
BEGIN
    -- 获取当前库存量
    SELECT stock_quantity INTO current_stock 
    FROM inventory 
    WHERE book_id = NEW.book_id
    FOR UPDATE;  -- 加锁防止并发冲突

    -- 校验库存是否充足
    IF current_stock IS NULL THEN
        RAISE EXCEPTION '图书ID % 不存在于库存表中', NEW.book_id;
    ELSIF current_stock < NEW.quantity THEN
        RAISE EXCEPTION '出库失败：图书 % 库存不足（当前：%，需求：%）', 
            NEW.book_id, current_stock, NEW.quantity;
    END IF;

    -- 更新库存（减少出库量）
    UPDATE inventory 
    SET stock_quantity = stock_quantity - NEW.quantity,
        last_updated = NOW()
    WHERE book_id = NEW.book_id;

    RETURN NEW;
END;
$function$;

-- Views
CREATE OR REPLACE VIEW "public"."v_bestsellers" AS
 SELECT to_char(so.sale_date, 'YYYY-MM'::text) AS sales_month, b.book_id, 
    b.title, b.author, sum(sd.quantity) AS total_quantity
   FROM sales_order so
   JOIN sales_detail sd ON so.order_id::text = sd.order_id::text
   JOIN book b ON sd.book_id::text = b.book_id::text
  GROUP BY to_char(so.sale_date, 'YYYY-MM'::text), b.book_id, b.title, b.author
  ORDER BY sum(sd.quantity);

CREATE OR REPLACE VIEW "public"."v_low_quantity_books" AS
 SELECT b.book_id, b.title, i.stock_quantity, i.last_updated
   FROM inventory i
   JOIN book b USING (book_id)
  WHERE i.stock_quantity <= 50;

CREATE OR REPLACE VIEW "public"."v_num_book_cat" AS
 SELECT b_c.category_id, b_c.category_name, 
    sum(i.stock_quantity) AS total_stock
   FROM book_category b_c
   JOIN book b ON b_c.category_id::text = b.category_id::text
   JOIN inventory i ON b.book_id::text = i.book_id::text
  GROUP BY b_c.category_id;

CREATE OR REPLACE VIEW "public"."v_publisher_supply" AS
 SELECT p.publisher_id, p.address, count(DISTINCT b.book_id) AS book_count, 
    COALESCE(sum(pd.quantity), 0::bigint) AS total_supplied, 
    COALESCE(sum(pd.quantity::numeric * pd.purchase_price), 0::numeric) AS total_amount
   FROM publisher p
   LEFT JOIN book b ON p.publisher_id::text = b.publisher_id::text
   LEFT JOIN purchase_detail pd ON b.book_id::text = pd.book_id::text
  GROUP BY p.publisher_id, p.address;

-- Triggers
DROP TRIGGER IF EXISTS "trg_after_purchase" ON purchase_detail;
CREATE TRIGGER trg_after_purchase AFTER INSERT ON purchase_detail FOR EACH ROW EXECUTE PROCEDURE update_inventory_on_purchase();

DROP TRIGGER IF EXISTS "trg_before_sale" ON sales_detail;
CREATE TRIGGER trg_before_sale BEFORE INSERT ON sales_detail FOR EACH ROW EXECUTE PROCEDURE update_inventory_on_sale();

